"""
/***************************************************************************
 Riverscapes Viewer
                                 A QGIS plugin
 Explore symbolized Riverscapes projects
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-13
        copyright            : (C) 2021 by North Arrow Research
        email                : info@northarrowresearch.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load QRAVE class from file QRAVE.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .__version__ import __version__  # noqa: F401
    from .src.qrave_toolbar import QRAVE

    return QRAVE(iface)
