# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QRAVE
                                 A QGIS plugin
 Explore symbolized Riverscapes projects
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-04-13
        git sha              : $Format:%H$
        copyright            : (C) 2021 by North Arrow Research
        email                : info@northarrowresearch.com
 ***************************************************************************/
"""
import os.path
from time import time
from functools import partial
from qgis.utils import showPluginHelp
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QUrl, pyqtSlot
from qgis.PyQt.QtGui import QIcon, QDesktopServices
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QToolButton, QMenu, QDialogButtonBox

from .classes.settings import Settings, CONSTANTS
from .classes.net_sync import NetSync
from .classes.async_worker import QAsync
from .classes.basemaps import BaseMaps
from .classes.project import Project


# Initialize Qt resources from file resources.py
# Import the code for the dialog
from .options_dialog import OptionsDialog
from .progress_dialog import ProgressDialog
from .about_dialog import AboutDialog
from .dock_widget import QRAVEDockWidget

# initialize Qt resources from file resources.py
from . import resources


class QRAVE:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.pluginIsActive = False
        self.dockwidget = None
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'QRAVE_{}.qm'.format(locale))
        self.settings = Settings()

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Riverscapes Plugin (QRAVE)')

        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'QRAVE')
        self.toolbar.setObjectName(u'QRAVE')

    # noinspection PyMethodMayBeStatic

    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('QRAVE', message)

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        plugin_init = self.settings.getValue('initialized')

        openAction = QAction(QIcon(':/plugins/qrave_toolbar/RaveAddIn_16px.png'), self.tr(u'Riverscapes Plugin (QRAVE)'), self.iface.mainWindow())
        openAction.triggered.connect(self.toggle_widget)
        openAction.setEnabled(plugin_init)
        openAction.setStatusTip('do a thing')
        openAction.setWhatsThis('what\'s this')

        openProjectAction = QAction(QIcon(':/plugins/qrave_toolbar/OpenProject.png'), self.tr(u'Open Riverscapes Project'), self.iface.mainWindow())
        openProjectAction.triggered.connect(self.projectBrowserDlg)
        openProjectAction.setEnabled(plugin_init)
        openProjectAction.setStatusTip('do a thing')
        openProjectAction.setWhatsThis('what\'s this')

        helpButton = QToolButton()
        helpButton.setMenu(QMenu())
        helpButton.setPopupMode(QToolButton.MenuButtonPopup)

        m = helpButton.menu()

        def openUrl():
            QDesktopServices.openUrl(QUrl("http://rave.riverscapes.xyz"))

        helpAction = QAction(
            self.tr('Help'),
            self.iface.mainWindow()
        )
        helpAction.triggered.connect(partial(showPluginHelp, None, filename=':/plugins/qrave_toolbar/help/build/html/index'))
        websiteAction = QAction(
            self.tr('Website'),
            self.iface.mainWindow()
        )
        websiteAction.triggered.connect(openUrl)

        raveOptionsAction = QAction(
            self.tr('Settings'),
            self.iface.mainWindow()
        )
        raveOptionsAction.setEnabled(plugin_init)
        raveOptionsAction.triggered.connect(self.optionsLoad)

        netSyncAction = QAction(
            self.tr('Update resources'),
            self.iface.mainWindow()
        )
        netSyncAction.triggered.connect(self.netSyncAction)

        aboutAction = QAction(
            self.tr('About QRAVE'),
            self.iface.mainWindow()
        )
        aboutAction.triggered.connect(self.aboutLoad)

        m.addAction(helpAction)
        m.addAction(websiteAction)
        m.addAction(raveOptionsAction)
        m.addAction(netSyncAction)
        m.addSeparator()
        m.addAction(aboutAction)
        helpButton.setDefaultAction(helpAction)

        self.toolbar.addAction(openAction)
        self.toolbar.addAction(openProjectAction)
        self.toolbar.addWidget(helpButton)

        # Run a network sync operation to get the latest stuff. Don't force it.
        #  This is just a quick check
        self.netSyncLoad()

    def netSyncAction(self):
        self.netSyncLoad(force=True)

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        # print "** CLOSING QRAVE DockWidget"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Riverscapes Plugin (QRAVE)'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    def projectBrowserDlg(self):
        """
        Browse for a project directory
        :return:
        """
        project_dir = QFileDialog.getExistingDirectory(self.dockwidget, "Open a project folder", self.settings.getValue('lastProjectDir'))
        if project_dir is not None and project_dir != "" and os.path.isdir(project_dir):
            project = Project(os.path.join(project_dir, 'project.rs.xml'))
            project.load()

    def optionsLoad(self):
        """
        Open the options/settings dialog
        """
        dialog = OptionsDialog()
        dialog.exec_()

    def aboutLoad(self):
        """
        Open the About dialog
        """
        dialog = AboutDialog()
        dialog.exec_()

    def netSyncLoad(self, force=False):
        """
        Periodically check for new files
        """

        lastDigestSync = self.settings.getValue('lastDigestSync')
        currTime = int(time())  # timestamp in seconds
        plugin_init = self.settings.getValue('initialized')
        dialog = ProgressDialog()
        dialog.setWindowTitle('QRAVE Updater')
        netsync = NetSync(dialog.progressLabel.setText, dialog.progressBar.setValue)

        # No sync necessary in some cases
        if plugin_init \
                and not netsync.need_sync \
                and not force \
                and isinstance(lastDigestSync, int) \
                and ((currTime - lastDigestSync) / 3600) < CONSTANTS['digestSyncFreqHours']:
            return

        async_job = QAsync(netsync.run)

        # Fire the tree change signal to repaint the basemaps
        async_job.worker.finished.connect(lambda: dialog.handle_done(force))
        async_job.worker.finished.connect(self.reload_tree)
        async_job.run()
        dialog.exec_()

    def reload_tree(self):
        """
        The dockwidget may or may not be initialized when we call reload so we
        add a checking step in
        """
        basemaps = BaseMaps()
        basemaps.load()
        if self.dockwidget:
            self.dockwidget.dataChange.emit()

    def toggle_widget(self, forceOn=False):
        """Toggle the widget open and closed when clicking the toolbar"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            # print "** STARTING QRAVE"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget is None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = QRAVEDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
        else:
            if self.dockwidget.isHidden():
                self.dockwidget.show()
            elif forceOn is False:
                self.dockwidget.hide()
